import requests
import time
import os

def download_large_file(url: str, filename: str, chunk_size: int = 8192):
    """
    Downloads a large file in chunks without loading the entire file into memory.
    """
    print(f"Starting download from {url}...")
    start_time = time.time()
    
    # stream=True prevents requests from downloading the body immediately
    with requests.get(url, stream=True) as response:
        response.raise_for_status()
        
        # Try to get the total size for a progress calculation (may not be present)
        total_size = response.headers.get('content-length')
        if total_size:
            total_size = int(total_size)
            print(f"Total file size: {total_size / (1024 * 1024):.2f} MB")
        else:
            print("Total file size unknown (likely chunked encoding).")
            
        downloaded = 0
        
        with open(filename, 'wb') as f:
            # iter_content yields chunks of bytes as they arrive from the network
            for chunk in response.iter_content(chunk_size=chunk_size):
                if chunk: # filter out keep-alive new chunks
                    f.write(chunk)
                    downloaded += len(chunk)
                    # Print progress (simplified)
                    if downloaded % (chunk_size * 100) == 0:
                        print(f"Downloaded {downloaded / 1024:.2f} KB...")
                        
    elapsed = time.time() - start_time
    print(f"Download complete! Saved to {filename}. Took {elapsed:.2f} seconds.")

def stream_lines(url: str):
    """
    Connects to a streaming endpoint that yields text line by line.
    (httpbin.org/stream/N generates N lines of JSON data)
    """
    print(f"\nConnecting to streaming endpoint: {url}")
    with requests.get(url, stream=True) as response:
        response.raise_for_status()
        
        # iter_lines yields one line at a time
        line_count = 0
        for line in response.iter_lines():
            if line: # filter out keep-alive new lines
                line_count += 1
                print(f"Line {line_count}: {line.decode('utf-8')[:50]}...")
                
    print("Stream ended.")

if __name__ == "__main__":
    # Example 1: Download a "large" file (a 10MB file generated by httpbin)
    # Note: httpbin handles /bytes/ by generating random data
    dummy_file_url = "https://httpbin.org/bytes/10485760" 
    download_large_file(dummy_file_url, "test_10mb.bin")
    
    # Cleanup
    if os.path.exists("test_10mb.bin"):
        os.remove("test_10mb.bin")
        
    # Example 2: Stream line-delimited JSON
    stream_lines("https://httpbin.org/stream/5")
